[client]
showSidebarNavigation = false

[theme]
primaryColor = "#BEB09E"
backgroundColor = "#F6F6F3"
secondaryBackgroundColor = "#D6D6D6"
textColor = "#335095"
font = "monospace"

[server]
maxUploadSize = 50